spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/itsdb
        username: root
        password: ark_angel
    server:
        port:8080        
    jpa:
        generate-ddl: true
        show-sql: true
        
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQLDialect
            
            